### ISSUE TITLE
Automatic saving when exiting the page 

### ISSUE THREAD

**Issue by Domhnall101** [CenterForDigitalHumanities/TPEN28#112]
Automatic saving when exiting the page (transcription.js "$(".exitPage").click(function(event)")

**Comment by thehabes** [comment]
These are all the things that require a save like when exiting the page:
- Any link out of the page (like T-PEN home)
- Any browser back or forward
- Any browser close
- Any browser tab close
- Any browser refresh

I will see which ones I can cover out of these.

**Comment by thehabes** [comment]
Any parsing or transcription changes take place automatically, so we may not really need this.  The only situations of these I can guarantee I can handle is linking out of the page.  The function we require is AJAX and there is no guarantee the call will complete successfully because we can't really overwrite default browser behavior and have the AJAX call.  

For the browser buttons, we can pop up a box that says "You will be navigating away from this page and may have unsaved data.  Are you sure?" or something and if the user clicks yes the redirect will happen and if they click no the redirect will not happen.  However, in some browsers, a default message pops up and is not customizable.

This one may require more discussion before moving forward with it.  I am punting for now.

**Comment by cubap** [comment]
the onBeforeUnload may be helpful here. I don't think we need to warn them at all, just make sure the autosave fires and completes before leaving the page. This is the current line 3303 in transcription.js

~~~
    $(".exitPage").click(function(event) {
      var thisLink = $(this).attr("href");
      if (isUnsaved()) {
        event.preventDefault();
        $("body").ajaxStart(function() {
          $(this).addClass("ui-state-disabled");
        }).ajaxStop(function() {
          if (thisLink.indexOf("?") != -1)
            thisLink += "&tool=" + liveTool;
          document.location = thisLink;
        });
        Data.saveTranscription();
        if (leftovers != undefined)
          Linebreak.saveLeftovers(escape(leftovers));
      } else {
        document.location = thisLink;
      }
    });
~~~~~

I just add the class to everything that may request a change that will lose data. It doesn't cover closing the tab, but interactions within the app are covered.
