### ISSUE TITLE
Enable splitscreen <select> when in a tool as a way to switch

### ISSUE THREAD

**Issue by cubap** [CenterForDigitalHumanities/TPEN28#139]

**Comment by thehabes** [comment]
Really test switching from tool to tool when you do this.  I originally implemented the disable because it screwed up the interface so bad either in the switch or when returning to full screen or when getting into the parsing interface.  There have been a lot of optimizations at this point, so this may be possible and may "just work".  The main time for this is TESTING.  a lot.
