### ISSUE TITLE
Button and parameter for -'work in classic/work in new' switch

### ISSUE THREAD

**Issue by Domhnall101** [CenterForDigitalHumanities/TPEN28#227]

**Comment by thehabes** [comment]
For this, the button should be .exitPage.  All it needs to do is href="transcription.jsp?projectID=x&p=y" where x and y are the parameters you already have in the URL on transcription.html.  Then it will go to the transcription classic page, bringing with it all the changes you had done on transcription.html because it was .exitPage .

**Comment by thehabes** [comment]
Stealing this from Patrick, I made some changes in other code for testing transcription.jsp and I want to test it to make sure it is a flawless transition with the button
