### ISSUE TITLE
bad .resources check on canvasObj in drawLinesToCanvas()

### ISSUE THREAD

**Issue by cubap** [CenterForDigitalHumanities/TPEN28#228]
expect .otherContent instead and deprecate "getAnno"

**Comment by thehabes** [comment]
It is because the next and prev page buttons in the header were give .exitPage.  .exitPage said to bulk update the lines (which in turn updates the dereferenced list), but that was meant for parsing and teh function expected HTML elements not JSON objects, so it broke the lines and the interface when changing the page.

Prev and Next page do not need .exitPage or the saveTranscription() functionality to fire because it is guaranteed that everything is saved EXCEPT the .activeLine.  I update the .activeLine in prev and nextFolio, so I removed the class .exitPage from their elements and everything works as it should.  

I fixed the bulk updater so that in cases where all the lines need to be updated, instead of sending the JSON lines we grab all the lines in the interface and pass those in instead.  However, there is no existing bulk updater for T-PEN that handles line position AND text, and the one that we wrote only works with the annotation store, so I have to update each line individually.  This may cause issues with the intended .exitPage functionality when relocating to a new page.  If this proves unsuccessful, we will have to write a new bulk update for this round of T-PEN that sends in all the JSON lines and gets them all updated in the SQL DB in one call.
