### ISSUE TITLE
special characters and xml tags seem to have lost their formatting on project.jsp

### ISSUE THREAD

**Issue by cubap** [CenterForDigitalHumanities/TPEN28#270]
![image](https://cloud.githubusercontent.com/assets/1119165/22056002/71d0c24e-dd23-11e6-868b-4b5891b6349d.png)

**Comment by thehabes** [comment]
Alright this one is a mess in the back end.  project.jsp says
```javascript
        <h6>Special Character Buttons</h6><%
                   Hotkey ha;
                    ha = new Hotkey(projectID, true);
                   /**Retrieve stored button information*/
                  out.print(ha.javascriptToAddProjectButtons(projectID));
          %>
```

```javascript
<h6>XML Tags</h6>
<div id="allXML"><%
/**Retrieve stored button information*/
     String buttons = TagButton.getAllProjectButtons(projectID);
     JSONArray buttons_obj = JSONArray.fromObject(buttons);
     for(int i=0; i<buttons_obj.size(); i++){
          JSONObject thisButton = buttons_obj.getJSONObject(i);
          out.print(thisButton.getString("tag")+"<br>");
       }
```

For the special characters, it looks like there is a deprecated and a new javascriptToAddProjectButtons.  The new one outputs `toret += "&#" + rs.getInt("key")+";<br>";`  while the deprecated one outputs `toret += "<span class=\"lookLikeButtons\"  onclick=\"Interaction.addchar('&#" + rs.getInt("key") + ";');\">&#" + rs.getInt("key") + ";<sup>" + rs.getInt("position") + "</sup></span>";`

This is deprecated because it is used by getProjectTPENServlet and we did not want HTML elements in there.

For XML tags, it looks like I completely rewrote this so that it retuns a JSONArray I can handle on the front end in project.jsp.  The old was used to do this

```javascript
int position = rs.getInt("position");
 try {
   TagButton b = new TagButton(projectID, position, true);
   toret += b.getButton();
  }
```
and getButton() would return

`<span class=\"lookLikeButtons\" title=\"" + getFullTag() + "\" onclick=\"Interaction.insertTag('" + tag + "', '" + getFullTag() + "');\">" + getDescription() + "</span>"`

The new one makes these and returns them
```javascript
try {
               TagButton b = new TagButton(projectID, position, true);
                ctr++;
                JSONObject jo = new JSONObject();
                if(null != b.getTag() && !"".equals(b.getTag())){
                    jo.element("tag", b.getTag()); //b.getButton()
                }
                else{
                    jo.element("tag", ""); //b.getButton()
                }
                if(null != b.getparameters() && b.getparameters().length != 0){
                    jo.element("parameters", b.getparameters());
                }
                else{
                    jo.element("parameters",blank_case);
                }
                if(null != b.getDescription()&& !"".equals(b.getDescription())){
                    jo.element("description", b.getDescription());
                }
                else{
                    jo.element("description","");
                }
                //jo.element("color", b.getXMLColor());
                ja.add(jo);
   }
```
This was also changed so it could be used with getProjectTPENServlet.

There are a couple options for moving forward with this.  We can either reinstate the original functionality for use ONLY in project.jsp, or we can wrap our data in HTML with the client on project.jsp.  Either way, it is a rather quick fix.

**Comment by cubap** [comment]
That's what I thought had happened. Your solutions are perfect. I have no
preference. I would probably wrap the output on the client, but that's what
I'm better at.  For 2.x, it doesn't really matter what happens.

**Comment by thehabes** [comment]
Perhaps the fact that buttonSchemaImport.jsp is broken means I should do it on the back end.  Otherwise, I will have to do it on the client in two places...

**Comment by thehabes** [comment]
The tags and special characters are coming through on project.jsp and transcription.html and transcription.jsp and buttonSchemaImport.jsp.  This is directly related to #271 and also is fixed with that issues as well.  This will not be available for review until 1/24's build.  Please note that  true test of buttonSchemaImport.jsp cannot be done unless deployed on prod.
