### ISSUE TITLE
buttonSchemaImport.jsp doesn't get the tags it expects

### ISSUE THREAD

**Issue by cubap** [CenterForDigitalHumanities/TPEN28#271]
Probably getTags() was altered and now HTML is not returned, but it is a mess.

**Comment by thehabes** [comment]
See the description in #270, these are directly related and likely a fix in one will fix the other.

**Comment by thehabes** [comment]
The tags and special characters are coming through on project.jsp and transcription.html and transcription.jsp and buttonSchemaImport.jsp.  This is directly related to #271 and also is fixed with that issues as well.  This will not be available for review until 1/24's build.  Please note that  true test of buttonSchemaImport.jsp cannot be done unless deployed on prod.

**Comment by thehabes** [comment]
Step 1: Log into /TPEN28
Step 2: Click on 'Manage' for Tradamus Simple, or load /TPEN28/project.jsp?projectID=4080 directly
Step 3: Make a note of the XML tags you see in this tab.  Click the Options tab, then click on "Import buttons from linked schema".
Step 4: Under "Current Project Tags" you should see the same tags you saw on project.jsp. 

If in Step 4 you see the same tags as on project.jsp, this issue is resolved.  Any other problems are their own separate issue.

**Comment by thehabes** [comment]
The xml tags have their formatting across the board (transcription.html, project.jsp, buttonSchemaImport.jsp)
