### ISSUE TITLE
Edit Characters screen

### ISSUE THREAD

**Issue by Domhnall101** [CenterForDigitalHumanities/TPEN28#277]
Edit Characters button goes to correct interface but there is no return to transcribing button present.

**Comment by cubap** [comment]
dependent on #249. The .exitPage handler is interrupting the normal application of a projectID, which is required for the "Return to Transcribing" button to appear.

**Comment by thehabes** [comment]
Problem 1 is the edit button is not .exitPage.  Problem 2 is that buttons.jsp does not have a [Return to Transcribing] button.  Problem 3 is that exitPage functionality is not working quite right, however problem 3 is technically unrelated to this issue.  Solve Problem 1 and Problem 2 and this issue is solved.

**Comment by thehabes** [comment]
up for review on 1/25 build
