### ISSUE TITLE
Split Screen - styling split screen adjustment and bug

### ISSUE THREAD

**Issue by Domhnall101** [CenterForDigitalHumanities/TPEN28#282]
1. The styling is inconsistent between split screen, parsing window and page tools.

![screen shot 2017-01-18 at 10 22 08 am](https://cloud.githubusercontent.com/assets/17204541/22074254/5e1a9e7e-dd6d-11e6-9569-137e81af2e64.png)
![screen shot 2017-01-18 at 10 25 17 am](https://cloud.githubusercontent.com/assets/17204541/22074279/74191e62-dd6d-11e6-80d3-a2f9d3fe65d8.png)

STYLE AS FOLLOWS: grey bar no drop shadow
![screen shot 2017-01-18 at 11 03 43 am](https://cloud.githubusercontent.com/assets/17204541/22074390/d8d89d14-dd6d-11e6-8655-5ebf2796048f.png)

2. When page tools window is clicked transcription window  narrows

![screen shot 2017-01-18 at 10 25 17 am](https://cloud.githubusercontent.com/assets/17204541/22074248/5a985638-dd6d-11e6-9cc1-63e5fa089925.png)
![screen shot 2017-01-18 at 10 25 31 am](https://cloud.githubusercontent.com/assets/17204541/22074316/953b6eb0-dd6d-11e6-9c44-6e018bb9f87c.png)

**Comment by thehabes** [comment]
If you see the drop shadow, it is because there is actually space between the split window and the transcription window.  This is because doing the math to keep the areas to take up exactly 100% of the window area is dangerous, it causes the page to wrap somewhat unexpectedly, so I try to keep it around 98%.  I made the 2% the buffer between the split area and the transcription area, but it does not have to be there.  Taking away the drop shadow all together will help with this.

In split situations where you see the gray bar, this means the window can be resized.  In split situations where the split UI is right up on the transcription interface without the gray bar, you cannot resize, which is why there was that difference.

**Comment by thehabes** [comment]
$("#transcriptionTemplate").resizeable() should not happen when the tool is "controls".  Make sure it is also destroyed.  check splitPage();

**Comment by Domhnall101** [comment]
Left size of grey bar allows for resizing. Shows one way arrow for cursor needs to be bidirectional
However,  right side should not show bi-directional arrow or any arrow at all as resize is not active there.

**Comment by cubap** [comment]
someone effed my code. I will put it back in.

**Comment by cubap** [comment]
k try now
