### ISSUE TITLE
INSPECT window 

### ISSUE THREAD

**Issue by Domhnall101** [CenterForDigitalHumanities/TPEN28#285]
inspect: style info box, make floating and put in upper right
![screen shot 2017-01-18 at 11 19 09 am](https://cloud.githubusercontent.com/assets/17204541/22075004/f6803b5e-dd6f-11e6-8f39-98486a0256e3.png)

**Comment by Domhnall101** [comment]
Revised look 
![screen shot 2017-01-18 at 2 54 08 pm](https://cloud.githubusercontent.com/assets/17204541/22082599/09c7c5a6-dd8e-11e6-9a14-f074a0e32b79.png)

**Comment by cubap** [comment]
This can almost be done. Since there is no cursor (it is the magnification) you cannot drag this box around. You can either push/chase it around (not great) or see through it when you reach it (current solution). In classic, the button for magnification was off the image, so this wasn't an issue, but this implementation needs something slightly different.

**Comment by thehabes** [comment]
Safest place to put it is topy righty, safest functionality is current functionality, return to transcription should not look like a button.  Double click to fire esc just in case there is no keyboard or something.

**Comment by thehabes** [comment]
Functions correctly
