### ISSUE TITLE
PARSING WINDOW - window resizing

### ISSUE THREAD

**Issue by Domhnall101** [CenterForDigitalHumanities/TPEN28#287]
very strange placement or content on page especially on window resizing
![screen shot 2017-01-18 at 10 42 32 am](https://cloud.githubusercontent.com/assets/17204541/22075155/76a9ce12-dd70-11e6-8e2d-ad7132f45f14.png)
![screen shot 2017-01-18 at 10 42 22 am](https://cloud.githubusercontent.com/assets/17204541/22075162/7c52eb32-dd70-11e6-960e-7e91699f5e54.png)

**Comment by thehabes** [comment]
Yeah this is because I center the interface (a little test project).  It doesn't know what do with it when you resize the window though, it should just need some CSS.  This wouldn't happen if it were left aligned, so the question is how much do you like it center aligned?  Remember, the image is sized for its maximum height/width here for optimal parsing, so the user isn't allowed to resize this tool like the others, which is why I centered it.  Definitely doesn't have to be this way though, like I said I was just really toying with the idea but I ended up liking it enough to put it in there and get your reaction.

**Comment by cubap** [comment]
What is the only check on resize is if the width of the tools (which I believe is fixed) + the image width is more than Page.width(), set the centerDiv to left align instead of center.

**Comment by thehabes** [comment]
Fixed.  Note this will not be available for testing until 1/24/2017's build

**Comment by Domhnall101** [comment]
This loard as being centered then left justifies when window is resized. It needs to start left justifed

**Comment by thehabes** [comment]
This is expected functionality.  The user gets centered justified screen at full screen and left justified when not.  The centered interface is a bonus of being full screen and I want people to feel like they are supposed to stay full screen in this.  If you click and drag to resize the screen, starting when the screen is about full size, you will see how it works.  Resize takes into account the area where the tools are until a certain point.  Eventually, the image is becoming too small, so I let the height of the image take precedence at about tablet size, at which point the area in which the tools are is ignored to make room for the image.  The width at which this occurs is very easy to customize and I am not exactly sure what to do when we hit it, but the image should not be allowed to get very small in this interface because the idea is parsing.  I can show you when I get there if this doesn't make sense.

**Comment by thehabes** [comment]
Ah but if you enter the interface when you browser is not full screen, it is center interfaced.  That's confusing, I will fix that.

**Comment by thehabes** [comment]
The implementation with the attempted center interface idea will be at /TPEN8, the fully left aligned implementation will be at /TPEN9

**Comment by thehabes** [comment]
up and ready
