### ISSUE TITLE
Lines have double borders

### ISSUE THREAD

**Issue by thehabes** [CenterForDigitalHumanities/TPEN28#296]
If you click to show the lines in the interface, it appears as though they have double borders.  I had the same issue initially when I had converted the data over to the annotation store.  It is a 1-2px difference in height or top.  If you detect this small of a difference in the math between the line position, actually render it with the 1-2px difference added in to make it natural.  You can do this by comparing to linetop + lineheight of the line before. 

The math should be doing this now, so maybe this "fix" that made it work with the new data is actually breaking it with the old data.  I know where this is in the code. It is an ancient problem but now that we are using the old data again it has resurfaced.

**Comment by cubap** [comment]
Nope. It's my fault. When I made the opacity lighter for the lines, I doubled the width of the border, but the hover border is still 1px. Since there is no explicit "box-sizing" set, the border is drawn outside the width of the element and overlaps into the neighboring elements. The solution is to either set them back to 1px width (which overlaps still, but covers itself) or set box sizing to "border-box" which draws the border inside the element box, keeping any overlap from happening.

It is a style choice and I have no real preference.
