### ISSUE TITLE
Inspect - should not change position of image - BUG

### ISSUE THREAD

**Issue by Domhnall101** [CenterForDigitalHumanities/TPEN28#306]
Right now when one uses the inspect the page the image automatically adjusts to the top of the page.

THIS SHOULD NOT HAPPEN.
The images should remain exactly as it is and only the transcription tool should disappear.

**Comment by thehabes** [comment]
Yes I agree.  Clicking Inspect calls maginify() which in turn calls hideWorkspaceToSeeImage().  This is the wrong approach.  hideWorkspaceToSeeImage hides #transWorkspace and #imgTop and puts #imgBottom and #imgBottom img to a top of 0.  You don't even see all of the image.

This function is useful when magnifying in split screen because then you will see the full image on screen and it is useful for comparison.  However, when not in split screen, we want this to work differently.  We do want #transWorkspace, #imgTop and the transcription lines to disappear.  #imgBottom will automatically become the top most element, so we do not need to reposition it.  We need to give it the height of 100% so as much of the image will show as possible.  Most importantly, do not reposition #imgBottom img.  This is what causes the "adjust to the top of the page" problem.  If you leave #imgBottom img alone, the page will stay exactly where it is at.  

Shouldn't take too long, definitely needs to get done.  Look in magnify() and hideWorkspaceToSeeImage(), and either edit hideWorkspaceToSeeImage() or write a new helper function like it to call in magnify().
