### ISSUE TITLE
Image loading 

### ISSUE THREAD

**Issue by Domhnall101** [CenterForDigitalHumanities/TPEN28#337]
first time loading
http://165.134.241.141/TPEN/transcription.html?projectID=4080&p=105422
![screen shot 2017-01-31 at 9 43 15 am](https://cloud.githubusercontent.com/assets/17204541/22472105/31c4d6dc-e79a-11e6-9efc-0982bb88302f.png)
![screen shot 2017-01-31 at 9 43 07 am](https://cloud.githubusercontent.com/assets/17204541/22472106/347bc462-e79a-11e6-8be4-e234c31ab4b2.png)

but if i load
http://165.134.241.141/TPEN28/transcription.html?projectID=4080&p=105422

then going back to 
http://165.134.241.141/TPEN/transcription.html?projectID=4080&p=105422

it loads 

that seems a problems

**Comment by thehabes** [comment]
It is not a problem.  All the images are served from TPEN28 because that is in the properties file for how it is named, we do not change it for each deployment.  Therefore, to get your images in any other deployment, you must be logged into the TPEN28.  What you tested into a classic "We are not authorized to get your image" scenario.  This will not happen when TPEN28 is properly launched, its a side effect of being on dev and testing.

**Comment by cubap** [comment]
This is not a problem. This is how we told you to load a project.

**Comment by Domhnall101** [comment]
I'll put the ticket to done. Ur I need to keep it to remind me test on the
live version
