### ISSUE TITLE
No projects open other than Tradamus 3 including newly created projects

### ISSUE THREAD

**Issue by Domhnall101** [CenterForDigitalHumanities/TPEN28#372]
It cannot go live unless this working first.

1. existing projects wont open. - image wont load
2. Newly created projects wont load for the same reason.

preview image image is visable in window on left of project tab under manage projects
![screen shot 2017-02-22 at 2 31 11 pm](https://cloud.githubusercontent.com/assets/17204541/23230982/94a192e0-f90b-11e6-9a77-240969e00858.png)

**Comment by thehabes** [comment]
I can get many other projects to open.  The problem is that the new prod server does have the images/userimages folder, so any project that attempts to use an image from the directory breaks, which is a lot of projects.  Those will not load up until we bring that folder over.

**Comment by thehabes** [comment]
This is a problem.
I have made a .tar of the userimages directory on 165.134.241.71/images/.  I need to get it from there into 165.134.105.25/images/.  However, I do not sftp for those directories on the servers and 165.134.241.71/home/bhaberbe does not have enough space on it for me to copy the .tar over so that I can move it. I get this error "mv: writing `/home/bhaberbe/userimages_backup.tar.bz2': No space left on device".  
Need a server guy for this one.

**Comment by thehabes** [comment]
Sam has responded and is attempting a solution
