### ISSUE TITLE
Who can see the parsing button?

### ISSUE THREAD

**Issue by Domhnall101** [CenterForDigitalHumanities/TPEN28#414]
if a user is attached someone elses project the button is missing

**Comment by thehabes** [comment]
Could this be because of permissions?  What about public vs. private projects?  Need to investigate this, i also had it happen to me on a couple projects.  Not sure what the trigger is.

**Comment by thehabes** [comment]
Here is what governs whether or not you get to see the button...
```javascript
if((tpen.user.isAdmin || permissions.allow_public_modify || permissions.allow_public_modify_line_parsing) && $.inArray("parsing", tools) > -1 ){
        $("#parsingBtn").show();
```
Which means you have to be considered an admin or the public permissions must be set for the project for you to be able to see the parsing button.

tpen.user.isAdmin is governed by
```javascript
$.each(tpen.project.leaders, function(){
        count++;
        if (this.UID === parseInt(data.cuser)){ //Is the curent userID listed as a project leader?
            tpen.user.isAdmin = true;
            return false;
        }
        if(count == length){ //we did not find this user in the list of leaders.
            console.warn("Not an admin");
        }
    });
```
Which means you have to be listed as a leader of the project for the page you are on to have admin (which is the only way to see the parsing button for projects that aren't public).

For project 4080 on /TPEN28/, han.yan@valpo.edu cannot see the parsing button because
(tpen.user.isAdmin || permissions.allow_public_modify || permissions.allow_public_modify_line_parsing) is false, which means those permissions are not set for the project and I am not a leader.

I suppose the question is how exactly is this supposed to work?  Who can see the parsing buttons for a project?  All users that belong to that project, or just those who are deemed leaders?  In group management, it used to be possible to promote/demote users but that is now absent, do we need to bring that back?

**Comment by thehabes** [comment]
**When I log in as cubap@slu.edu (the leader) for project 4080, I have the ability to promote and demote users.  When I promote han.yan@valpo.edu, I was able to see the parsing button as that user.

**Comment by thehabes** [comment]
For newberry, we made it so that any Group Leader could demote a different Group Leader, but you cannot demote yourself.  This is in groups.html (the html version of groups.jsp), we would have to port this functionality over, unless we choose a different permission system by which a user can be granted permission to see the parsing button

**Comment by thehabes** [comment]
The decision is to stick with how it is working for now.

**Comment by thehabes** [comment]
also see #426
