### ISSUE TITLE
Merge line - causes black screen freeze

### ISSUE THREAD

**Issue by Domhnall101** [CenterForDigitalHumanities/TPEN28#424]

**Comment by thehabes** [comment]
Uncaught TypeError: Cannot read property 'replace' of undefined
    at updateLine (transcribe.js:3984)

`lineID = parseInt(lineID.replace("line/", ""));`

**Comment by thehabes** [comment]
Comes from a problem with tracking lines through tpen.screen.dereferencedLists vs tpen.manifest.sequences[0].canvases[index].otherContent[0].resources.  I should have evened it all up now.

**Comment by Domhnall101** [comment]
Delete line is now borken

**Comment by Domhnall101** [comment]
thisi s borken again and delete line works

**Comment by thehabes** [comment]
Tested merging various lines throughout the column and all tests passed using Windows 8.1, Chrome logged in as han.yan@valpo.edu on projects 5330, 5497 and 5555 at t-pen.org/TPEN28/. This is now up for testing at /TPEN28/

**Comment by thehabes** [comment]
Merging existing lines seems to work fine, but when you create new lines then start merging them, it acts up

**Comment by thehabes** [comment]
This is because of saveNewLine();  It did not pick up the fact that the lineid is 'line/123456' instead of just '123456'.  This makes updateLine() used in mergeLines unable to match an id within the list of known annotations, thus when the splice happens in the annotation array there is no update to fire on the line that needs an update so that it's size grows.

**Comment by thehabes** [comment]
cleanupTranscriptlets() at the end of saveNewLine() causes all `.transcriptlet` s to be removed, so actions performed from there on will be unsuccessful.  I am making it know to check for `.parsing` in these cases, which can be substituted for .transcriptlet.

**Comment by thehabes** [comment]
It was a very deep issue that was connected to the choice to disconnect from the annotation store data.  There were "@id" vs "tpen_line_id" inconsistencies and inconsistencies with tracking `tpen.manifest.sequences[0].canvases[tpen.screen.currentFolio].otherContent[0].resources` vs `tpen.screen.dereferencedLists[tpen.screen.currentFolio].resources = currentAnnoList;` between new lines and existing lines, which threw off the update and delete functions.  I believe it is all smoothed out,, I have been able to get through my adding and merging without issue on a couple projects now.

**Comment by cubap** [comment]
Merge on 28 at 21:33 15/03/17 on project 5147 resaves the top line without increasing the height and removes the second line (the UI shows the correct behavior, a refresh exposed the issue). Further, rather than merge the line from the top of the top line to the bottom of the bottom line, the heights are just added together, which causes issues if there are any gaps or overlaps. Even small differences (which are frequent) have a cumulative effect which cannot be corrected.

That said, the black screen freeze is corrected, so this can be reticketed.

**Comment by cubap** [comment]
Spoke too soon. Merging a smaller line into a larger line (after adjusting the right edge), breaks into the overlay. Larger into smaller seems to work, but shrinks to the smaller line, which would not be expected.

However, the error is this: `transcribe.js:3967 Uncaught TypeError: Cannot read property 'replace' of undefined` so `lineID` is undefined, so maybe something in the adjust process is removing that attribute.
