### ISSUE TITLE
Animations get shut off in 28 at some point

### ISSUE THREAD

**Issue by cubap** [CenterForDigitalHumanities/TPEN28#427]
On transcription.html, after peek-zooming and tabbing around, when I used CTRL+ALT to move the workspace, it jumped instead of sliding and then all the transitions were off. Looking quickly, it seems that CSS is handling the transitions instead of a class, as in classic, which may be leading to a crossed wire.

**Comment by thehabes** [comment]
check around the code for the class `.noTransition`.  A `.removeClass("noTransition")` probably needs to be included somewhere we missed it.

**Comment by thehabes** [comment]
added
`$("#imgTop img,#imgBottom img,#imgTop .lineColIndicatorArea, #imgBottom .lineColIndicatorArea, #bookmark, #imgTop, #imgBottom").removeClass('noTransition');`

into `fullPage()` because we know we want all transitions to be live at that point.  I also checked the functions that forgot to remove it, and it looks like `togglleMoveImage()` (ctrl + alt) was to blame, so I removeClass('.noTransition') in its toggle off.  That should fix this
