### ISSUE TITLE
Retrun to transcription button not working correctly

### ISSUE THREAD

**Issue by Domhnall101** [CenterForDigitalHumanities/TPEN28#469]
clicking the return to transcription button form the parsing interface the page does not load correctly. The header is missing , the lines are messed up and the tool bar is tuck at the top of hte page. A reload of this loads correctly. in the image below you can see the misplaced tool bar and the line selected is hiding behind the tool bar

![screen shot 2017-04-25 at 11 01 06 am](https://cloud.githubusercontent.com/assets/17204541/25395432/9fd468d8-29a6-11e7-88cd-5ea8b602d92e.png)

**Comment by thehabes** [comment]
This is confirmed.  I believe it is a mac and/or safari thing.   I cannot get the same projects that fail on the mac to fail on the PC.  However, @cubap suggested taking away any forced top positioning of imgTop and transcriptionCanvas since they don't need it and they have animations attached to them and this has been the cause of similar problems in the past.  

The plan of action is to take out all forced or CSS top positioning of imgTop and transcriptionCanvas, then test again on @Domhnall101 computer to see if this has any effect.  If this does not fix anything or breaks other things, then I can test on @Domhnall101 computer to find the root of the problem.  However, I believe at that point it should become a part of the Cross Browser/Cross Platform set of issues, which should be handled as a group, not individually.

**Comment by Domhnall101** [comment]
sounds like a viable solution. Let me know when you are ready to test



On Tue, Apr 25, 2017 at 1:34 PM, Bryan Haberberger <notifications@github.com
> wrote:

> This is confirmed. I believe it is a mac and/or safari thing. I cannot get
> the same projects that fail on the mac to fail on the PC. However, @cubap
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_cubap&d=DwMFaQ&c=Pk_HpaIpE_jAoEC9PLIWoQ&r=H-pvvm1AeDS_YWl-1yRNHg&m=LFeKO_F6xyJ3ZXVg4pqjd2QhGYlyDPZAG2KTWpgVU-o&s=8l1wWs0NJxXhArOD5RAxn4pRrnCGbvWwOHcPNcFHoCo&e=>
> suggested taking away any forced top positioning of imgTop and
> transcriptionCanvas since they don't need it and they have animations
> attached to them and this has been the cause of similar problems in the
> past.
>
> The plan of action is to take out all forced or CSS top positioning of
> imgTop and transcriptionCanvas, then test again on @Domhnall101
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_Domhnall101&d=DwMFaQ&c=Pk_HpaIpE_jAoEC9PLIWoQ&r=H-pvvm1AeDS_YWl-1yRNHg&m=LFeKO_F6xyJ3ZXVg4pqjd2QhGYlyDPZAG2KTWpgVU-o&s=7EAj4qNTEnuFcYT52YpzQQ2nPQ1JAmlDrMnGO82HG0Y&e=>
> computer to see if this has any effect. If this does not fix anything or
> breaks other things, then I can test on @Domhnall101
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_Domhnall101&d=DwMFaQ&c=Pk_HpaIpE_jAoEC9PLIWoQ&r=H-pvvm1AeDS_YWl-1yRNHg&m=LFeKO_F6xyJ3ZXVg4pqjd2QhGYlyDPZAG2KTWpgVU-o&s=7EAj4qNTEnuFcYT52YpzQQ2nPQ1JAmlDrMnGO82HG0Y&e=>
> computer to find the root of the problem. However, I believe at that point
> it should become a part of the Cross Browser/Cross Platform set of issues,
> which should be handled as a group, not individually.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_CenterForDigitalHumanities_TPEN28_issues_469-23issuecomment-2D297124608&d=DwMFaQ&c=Pk_HpaIpE_jAoEC9PLIWoQ&r=H-pvvm1AeDS_YWl-1yRNHg&m=LFeKO_F6xyJ3ZXVg4pqjd2QhGYlyDPZAG2KTWpgVU-o&s=QV8tY54nC-7SSg2OWnslky-Jb_pwUQpDkX2X5PVvFRk&e=>,
> or mute the thread
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AQaFPQKjiJG25iWOsp4cGqxcFnK2iu-2Doks5rzjzHgaJpZM4NHszW&d=DwMFaQ&c=Pk_HpaIpE_jAoEC9PLIWoQ&r=H-pvvm1AeDS_YWl-1yRNHg&m=LFeKO_F6xyJ3ZXVg4pqjd2QhGYlyDPZAG2KTWpgVU-o&s=5LsLwsc9--0ENACdXfKvjYqC9OrIn2IQbaz9NP13tRM&e=>
> .
>



-- 
Donal Hegarty
Project Manager/UX Designer
Walter J. Ong S.J. Center for Digital Humanities
Saint Louis University
314 9774248
