### ISSUE TITLE
Rendering issues on 2.8 and TPEN-NL transcription

### ISSUE THREAD

**Issue by cubap** [CenterForDigitalHumanities/TPEN28#504]
Two issues together, possibly related:

1. Columns (especially one line columns) can disappear when the previous column Y is different from the current line. The classic interface does not suffer the same perturbation.  Test at http://t-pen.org/TPEN/transcription.html?&projectID=6609&p=13238147 with user guest::guest.
2. Column labels go `undefined` after the 26 chars in the default array are used up.

**Comment by thehabes** [comment]
I brought over a TPEN.sql from prod to dev, I will be doing all these tests on dev so as not to mess up prod.  just a heads up.

**Comment by thehabes** [comment]
Found a good fix, tested with this project and project 4080.  You can test on dev at 

http://165.134.107.94/TPEN/transcription.html?&projectID=6609&p=13238147&liveTool=none
http://165.134.107.94/TPEN/transcription.html?&projectID=4080&liveTool=none&p=105420

Test with 4080 too because it has fringe cases, like what if your line is 1/4 the height of the page or at the very top of the page, etc.
