### ISSUE TITLE
Inviting New User Into Project 

### ISSUE THREAD

**Issue by thehabes** [CenterForDigitalHumanities/TPEN28#522]
When inviting someone who is not in T-PEN into a project via E-mail, the resulting E-mail to the invitee is
`
{{XYZ}} has invited you to join their transcription project on TPEN.  Your initial password is blank, please log in and set a password. 
The TPEN team
`
This should at least have a link to t-pen in it or something.

Upon going to T-PEN and trying to log in with a blank password, I am presented with the error

![aa](https://user-images.githubusercontent.com/3287006/75470809-dbeca500-5956-11ea-8c1d-e3a55fab03b9.png)

What is the pipeline for this supposed to be?

**Comment by cubap** [comment]
I saw this when I was reviewing and wasn't quite sure if it was in the users flow. The issue is that it sends an unsolicited email, so we don't want to suggest that we're doing too much on their behalf.

We create an account and tie it to the project when someone is invited. There is actually a temporary password created, not a blank one, so I'm not sure about that message. I propose to offer someone use the "reset password" to "create an account".
