### ISSUE TITLE
Changes to `tpen.user` intentional?

### ISSUE THREAD

**Issue by cubap** [CenterForDigitalHumanities/TPEN28#56]
I think there was user confusion that broke the captions, so I just fixed the symptom, but wanted to be sure this was an intentional move.

It used to be (before commit 426604aa097554152236bb2d8dbda14fb7d645c2) that tpen.user had only `current` and `isAdmin`, as these were all that was knowable about the logged in entity on the website. The `/geti` servlet would return the `uid` and `uname` only. The users in `project.leaders` and such would have full names. At any rate, an admin check would turn on `tpen.user.isAdmin` and the login servlet would just write the result into tpen.user, making for simple login checks (like d033ac5ff9989a5f0e63f67fd3b9f68efa857fbb). It looks like the new default tries to define a sort of in app user that has more features than we support (not more than can be known, but still). It also doesn't match the format of any of our servlet returns which means it would need to be transformed in and out of any http, which seems unhelpful.

I'm willing to go either way, since the permissions flags can be added easily to `tpen.user` without destroying the user and overwriting `tpen.user` with a new login would clear flags that should be cleared. There may be other places I had been looking inside `tpen.user.current` so let's watch for that.

**Comment by thehabes** [comment]
Yes, it was intentional.  That use object's extras get defined by returns in the getProjectTPENServlet.  The extras you note in the tpen.user object do not come from the /geti servlet.  They could just as well be stored in a 'tpen.project.user' since that where that user information actually came from, then we can leave the' tpen.user' piece pure.  

The only admin check I saw looked into ls_leaders[] from getProjectTPENServlet and does 

` if (ls_leader.UID === parseInt(data.cuser)){ 
tpen.user.isAdmin = true;
   }`
            
but at the point we know that, ls_leader also has fname, lname, and openID so I may as well capture that information and put it to tpen.user because that is valuable information about the current user.

So maybe it's that the admin check is wrong here.  but I figured if I am already doing the admin check this way, I can grab the user's other information as well.  We only do this in transcription.html, but project.html will have to do the same thing for the admin check.  The jsp pages do not use this logic.  I am also willing to go either way, basically the timing of it shaped how it was coded, I am not attached to it.
