### ISSUE TITLE
Login Weirdness (index.jsp)

### ISSUE THREAD

**Issue by thehabes** [CenterForDigitalHumanities/TPEN28#57]
Sometimes, whether I succeed or fail to login, and sometimes just when entering the page, the browser downloads a file named index,jsp

**Comment by cubap** [comment]
My guess is that the server is failing to render the page correctly, so instead of serving an HTML document, it sends a broke-ass file called index.jsp. The network monitor should be showing the pages that download as well, so you should see index.jsp. Since login is a reload on that page, you'd see it download again.

**Comment by cubap** [comment]
Definite wontfix. New login handling in 3.0 will take care of the issue.
