### ISSUE TITLE
Content Negotiation (Prezi 2 and Prezi 3)

### ISSUE THREAD

**Issue by thehabes** [CenterForDigitalHumanities/TPEN28#632]
https://iiif.io/api/presentation/3.0/#63-responses

**Comment by thehabes** [comment]
![image](https://user-images.githubusercontent.com/3287006/194155121-8a1cd06f-a8ec-4564-a0f4-3dd58924ce4a.png)

**Comment by markskroba** [comment]
ProjectServlet will return presi 2 when no `Accept` header is being specified in the request, and presi 3 if `Accept` header contains `iiif/v3`, allowing for other parameters, like in the examples of other `Accept` headers from above. Since usually applications return presi 3 by default (ie without `Accept` header), there was no standard to what the value for this header was supposed to be - `iiif/v3` was selected as it seem to follow the structure or syntax of `Accept` header, while also conveying what it is intended for.
