### ISSUE TITLE
Linebreaking Tool

### ISSUE THREAD

**Issue by thehabes** [CenterForDigitalHumanities/TPEN28#70]
When selecting "linebreak and proofread existing text", it just jumps into transcription.html hoping to load up the line breaking tool.  This tool does not exist in the transcription.html interface, so all the user gets is the normal transcription interface.

**Comment by cubap** [comment]
Okay... We can put it in, but it is really tricky because the uploader relies on a page reload and the jsp holding the file in memory are the user moves around. The alternative is to deprecate the "upload a file" option and just let people paste in the text and break it with ENTER. An in between option that may work would be to remove the upload bit from the split-screen tool and still allow inputting a linebreak character. I haven't considered the work involved in this yet...

I wish we had better analytics on who actually used this.

**Comment by cubap** [comment]
StringEscapeUtils.escapeJavaScript(thisProject.getLinebreakText()) should be available in the project object for use in TPEN, but is not right now. I can try to add it, but @thehabes is probably very quick in pulling this in.

**Comment by cubap** [comment]
Data.saveTranscription() was not brought over, and I cannot find if @thehabes made something like it that checks permissions and saves a whole page.

**Comment by thehabes** [comment]
Created javascript function in transcribe.js called batchLineUpdate(lines).  Created BulkUpdateAnnos.java which can be hit at /bulkUpdateAnnos.  This allows me to hand in an array of annotations for a Mongo bulk update.  batchLineUpdate(lines) will take the array of lines handed in to be updated and throw them at /bulkUpdateAnnos.

**Comment by thehabes** [comment]
Linebreaking text comes out in getProjectTPENServlet and gets put under project.remainingText.  Data.saveTranscription() will get the derferenced list's lines and bulk update each annotation individually and update the annotation list (since we don't do subdocuments).
